/**
 * Fahrzeugverwaltung
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetVehicleStatusResponseCurrentReservation } from './getVehicleStatusResponseCurrentReservation';
import { ReservationModelDto } from './reservationModelDto';
import { VehicleModelDto } from './vehicleModelDto';
import { VehicleStatus } from './vehicleStatus';


export interface GetVehicleStatusResponse { 
    vehicle?: VehicleModelDto;
    upcomingReservations?: Array<ReservationModelDto>;
    currentReservation?: GetVehicleStatusResponseCurrentReservation | null;
    vehicleStatus?: VehicleStatus;
}

