/**
 * Fahrzeugverwaltung
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetVehicleStatusResponseCurrentReservation } from './getVehicleStatusResponseCurrentReservation';
import { UserDto } from './userDto';
import { VehicleModelDto } from './vehicleModelDto';


export interface LogBookEntryDto { 
    id?: string;
    currentNumber?: number;
    description?: string | null;
    createdAt?: Date;
    createdBy?: UserDto;
    endMileageInKm?: number | null;
    associatedReservation?: GetVehicleStatusResponseCurrentReservation | null;
    associatedVehicle?: VehicleModelDto;
}

