/**
 * Fahrzeugverwaltung
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';
import { ReservationStatusModelDto } from './reservationStatusModelDto';
import { VehicleModelDto } from './vehicleModelDto';
import { ReservationStatusEnum } from './reservationStatusEnum';


export interface ReservationModelDto { 
    id?: string;
    reason?: string;
    startDateInclusive?: string;
    endDateInclusive?: string;
    originAdress?: string;
    destinationAdress?: string;
    reservationCreated?: Date;
    reservationMadeByUser?: UserDto;
    currentStatus?: ReservationStatusEnum;
    vehicleReserved?: VehicleModelDto;
    reservationStatusChanges?: Array<ReservationStatusModelDto>;
}

