export * from './default.service';
import { DefaultService } from './default.service';
export * from './ical.service';
import { IcalService } from './ical.service';
export * from './identity.service';
import { IdentityService } from './identity.service';
export * from './invitation.service';
import { InvitationService } from './invitation.service';
export * from './reservation.service';
import { ReservationService } from './reservation.service';
export * from './test.service';
import { TestService } from './test.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './vehicle.service';
import { VehicleService } from './vehicle.service';
export const APIS = [DefaultService, IcalService, IdentityService, InvitationService, ReservationService, TestService, UserService, VehicleService];
