version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mysql_data:/var/lib/mysql'  
  phpmyadmin:
    container_name: phymyadmin
    image: phpmyadmin
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "1338:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "15672:15672"
      - "5672:5672"
    
  # postgresql:
  #   container_name: keycloak-database
  #   image: docker.io/bitnami/postgresql:11
  #   environment:
  #     # ALLOW_EMPTY_PASSWORD is recommended only for development.
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - POSTGRESQL_USERNAME=bn_keycloak
  #     - POSTGRESQL_DATABASE=bitnami_keycloak
  #   volumes:
  #     - 'postgresql_data:/bitnami/postgresql'
      
  # keycloak:
  #   container_name: keycloak
  #   image: docker.io/bitnami/keycloak:18
  #   environment:
  #     - KEYCLOAK_CREATE_ADMIN_USER=true
  #     - KEYCLOAK_ADMIN_USER=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #   depends_on:
  #     - postgresql
  #   ports:
  #     - "1337:8080"
        
volumes:
  # postgresql_data:
  #   driver: local
  mysql_data:
    driver: local